(function(){
'use strict';
const $=id=>document.getElementById(id), data=JSON.parse($('kit-data').textContent), core=window.BuyerCore;
const labels={fit:'Possible fit',investigate:'Needs a check',pass:'Excluded',invalid:'Invalid row',duplicate:'Duplicate'};
let sourceText='',sourceLabel='',rows=[],results=[],activeRules=null,page=1,reviewId=null,loadToken=0,networkToken=0,scanId=null,networkBusy=false,networkController=null;const pageSize=20;
const split=value=>value.split(',').map(x=>x.trim()).filter(Boolean);
const rules=()=>Object.fromEntries(['roles','businesses','exclusions','locations'].map(key=>[key,split($(key).value)]));
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
function networkStatus(text,error=false){$('network-status').textContent=text;$('network-status').classList.toggle('error',error);}
function resetNetwork(){networkToken++;if(networkController)networkController.abort();networkController=null;networkBusy=false;scanId=null;$('network-submit').disabled=false;$('buyer-confirmation').hidden=true;$('network-submit').textContent='Continue ↗';$('network-step').textContent='Start with your profile';$('network-status').textContent='';invalidate();$('coverage-note').hidden=true;}
$('linkedin-url').addEventListener('input',()=>{resetNetwork();$('buyer-question').hidden=true;$('buyer-description').value='';});
$('buyer-description').addEventListener('input',resetNetwork);
$('change-buyer').addEventListener('click',()=>{resetNetwork();$('buyer-question').hidden=false;$('buyer-description').focus();});
function showNetworkResults(response){
  rows=response.rows;sourceLabel='Visible network';activeRules=response.criteria;results=core.analyze(rows,activeRules).results;page=1;
  ['roles','businesses','exclusions','locations'].forEach(key=>$(key).value=(activeRules[key]||[]).join(', '));
  $('status-filter').value='all';$('result-search').value='';$('prompt-result').hidden=true;$('results').hidden=false;
  $('coverage-note').textContent=response.coverage.scanned+' visible connections reviewed. '+response.coverage.note;$('coverage-note').hidden=false;
  render();$('results').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});
}
$('network-form').addEventListener('submit',async event=>{
  event.preventDefault();if(networkBusy)return;
  const value=$('linkedin-url').value.trim();let url;
  try{url=new URL(/^https?:\/\//i.test(value)?value:'https://'+value);if(!['linkedin.com','www.linkedin.com','m.linkedin.com'].includes(url.hostname.toLowerCase())||url.username||url.password||url.port||!/^\/in\/[^/]+\/?$/.test(url.pathname))throw new Error();}catch(_){networkStatus('Paste your LinkedIn profile link, such as linkedin.com/in/your-name.',true);$('linkedin-url').focus();return;}
  const token=++networkToken,scanning=Boolean(scanId),controller=new AbortController();networkController=controller;networkBusy=true;$('network-submit').disabled=true;
  networkStatus(scanning?'Checking visible connections against your buyer description…':'Reading your profile and buyer description…');
  try{
    if(location.protocol==='file:')throw new Error('Automatic profile lookup runs on the hosted tool. This offline copy includes the fictional report and optional CSV tool.');
    const response=await fetch(document.querySelector('meta[name=network-buyer-api]')?.content||'/api/network-buyer-finder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(scanning?{action:'scan',scan_id:scanId}:{action:'prepare',linkedin_url:value,buyer_description:$('buyer-description').value.trim()}),signal:AbortSignal.any([controller.signal,AbortSignal.timeout(60000)])});
    let payload;try{payload=await response.json();}catch(_){throw new Error('Automatic profile lookup is not connected in this preview yet. You can see the fictional report below.');}
    if(token!==networkToken)return;
    if(!response.ok)throw new Error(payload.error||'The profile lookup is temporarily unavailable. Try again later.');
    if(payload.status==='needs_buyer'){$('buyer-question').hidden=false;$('network-step').textContent='Add a little context';networkStatus('Your profile needs a little more context. Who do you sell to?');$('buyer-description').focus();}
    else if(payload.status==='confirm_buyer'){
      scanId=payload.scan_id;$('buyer-summary').textContent=payload.criteria.summary;$('buyer-rules').replaceChildren(...[['roles','Buyer roles'],['businesses','Business types'],['exclusions','Exclude'],['locations','Locations']].filter(([key])=>payload.criteria[key]?.length).map(([key,label])=>element('p',label+': '+payload.criteria[key].join(', '),'small')));$('buyer-evidence').textContent=(payload.criteria.evidence||[]).join(' · ');$('buyer-confirmation').hidden=false;$('buyer-question').hidden=true;$('network-step').textContent='Check your buyer description';$('network-submit').textContent='Find possible buyers ↗';networkStatus('Check these roles and business types, then confirm to start your network lookup.');
    }else if(payload.status==='complete'){
      scanId=null;showNetworkResults(payload);$('network-step').textContent='Your first pass is ready';$('network-submit').textContent='Start another lookup ↗';networkStatus('Your visible-network results are ready to review.');
    }else throw new Error('The lookup returned an unreadable response. Please start again.');
  }catch(error){if(token===networkToken){if(scanning){scanId=null;$('network-submit').textContent='Start again ↗';}networkStatus(error.name==='TimeoutError'?'The lookup took too long. Try again shortly.':error.message,true);}}
  finally{if(networkController===controller){networkController=null;networkBusy=false;$('network-submit').disabled=false;}}
});
$('network-demo').addEventListener('click',()=>{resetNetwork();$('load-demo').click();$('finder-form').requestSubmit();$('coverage-note').hidden=false;$('coverage-note').textContent='Fictional report. These people and companies are invented. No LinkedIn lookup ran.';});
function status(text,error=false){$('tool-status').textContent=text;$('tool-status').classList.toggle('error',error);}
function invalidate(){if($('review-dialog').open)$('review-dialog').close();reviewId=null;if(!$('results').hidden){results=[];$('results').hidden=true;$('prompt-result').hidden=true;status('Your input changed. Run the finder again to update the decisions.');}}
function setSource(text,label){resetNetwork();sourceText=text;sourceLabel=label;$('csv-input').value=text;$('file-note').textContent=label+' · Ready to review. Your CSV stays in this browser.';invalidate();$('coverage-note').hidden=true;status('CSV loaded. Check the criteria, then find possible buyers.');}
async function loadFile(file){if(!file)return;resetNetwork();const token=++loadToken;invalidate();if(file.size>40*1024*1024){sourceText='';$('csv-input').value='';status('Choose a CSV smaller than 40 MB.',true);return;}try{const text=await file.text();if(token!==loadToken)return;setSource(text,file.name);}catch(_){status('This file could not be read. Try choosing it again.',true);}}
$('csv-file').addEventListener('change',event=>loadFile(event.target.files[0]));
$('csv-input').addEventListener('input',()=>{resetNetwork();loadToken++;sourceText=$('csv-input').value;sourceLabel='Pasted CSV';invalidate();});
['roles','businesses','exclusions','locations'].forEach(key=>$(key).addEventListener('input',resetNetwork));
$('load-demo').addEventListener('click',()=>{loadToken++;['roles','businesses','exclusions','locations'].forEach(key=>{if(data.defaults&&data.defaults[key])$(key).value=data.defaults[key].join(', ');});setSource(data.demoCsv||'','Fictional example');});
const drop=$('drop-zone');['dragenter','dragover'].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.add('dragging');}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,event=>{event.preventDefault();drop.classList.remove('dragging');}));drop.addEventListener('drop',event=>loadFile(event.dataTransfer.files[0]));
$('finder-form').addEventListener('submit',event=>{event.preventDefault();resetNetwork();const input=$('csv-input').value||sourceText;if(!input.trim()){status('Choose a connections CSV, paste one or try the fictional example.',true);return;}try{const nextRows=core.parseCsv(input);if(!nextRows.length)throw new Error('The CSV has a header but no connection rows.');const nextRules=rules();if(!nextRules.roles.length||!nextRules.businesses.length)throw new Error('Add at least one buyer role and one business type.');const analyzed=core.analyze(nextRows,nextRules);rows=nextRows;results=analyzed.results;activeRules=nextRules;page=1;$('status-filter').value='all';$('result-search').value='';$('results').hidden=false;$('prompt-result').hidden=true;render();status('Reviewed '+rows.length+' rows. Open the results to check each decision.');$('results').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}catch(error){status(error.message,true);}});
function visibleResults(){const filter=$('status-filter').value,search=$('result-search').value.trim().toLowerCase();return results.filter(row=>(filter==='all'||row.status===filter)&&(!search||[row.name,row.company,row.title].join(' ').toLowerCase().includes(search))).sort((a,b)=>{const order={fit:0,investigate:1,pass:2,invalid:3,duplicate:4};return order[a.status]-order[b.status]||(b.priority||0)-(a.priority||0)||a.sourceRow-b.sourceRow;});}
function render(){const counts={fit:0,investigate:0,pass:0,invalid:0,duplicate:0};results.forEach(row=>counts[row.status]++);$('counts').replaceChildren(...Object.entries(counts).map(([key,count])=>{const node=element('div',undefined,'count');node.append(element('strong',String(count)),element('span',({fit:'Possible fits',investigate:'Need a check',pass:'Excluded',invalid:'Invalid rows',duplicate:'Duplicates'})[key]));return node;}));$('result-source').textContent=sourceLabel==='Fictional example'?'Fictional example results':'Your connections, reviewed';$('result-summary').textContent=results.length+' rows accounted for. Each decision includes its reason. Missing facts need your review.';const visible=visibleResults(),pages=Math.max(1,Math.ceil(visible.length/pageSize));page=Math.min(page,pages);const list=$('result-list');list.replaceChildren();visible.slice((page-1)*pageSize,page*pageSize).forEach(row=>{const button=element('button',undefined,'result-row');button.type='button';button.dataset.rowId=row.id;button.setAttribute('aria-label','Review '+(row.name||'row '+row.sourceRow)+': '+labels[row.status]);const person=element('div');person.append(element('strong',row.name||'Unnamed connection'),element('span',[row.title,row.company].filter(Boolean).join(' · ')||'No role or company supplied','person-title'));const reason=element('div',row.reason,'row-reason');if(row.engaged===true)reason.append(element('span','Prior engagement supplied','small'));button.append(person,reason,element('span',labels[row.status],'badge '+row.status),element('span','↗','row-arrow'));button.addEventListener('click',()=>openReview(row.id));list.append(button);});if(!visible.length)list.append(element('p','No rows match this filter. Try another decision or search.','empty-list'));$('page-status').textContent=visible.length?'Showing '+((page-1)*pageSize+1)+'–'+Math.min(page*pageSize,visible.length)+' of '+visible.length:'0 rows';$('prev-page').disabled=page===1;$('next-page').disabled=page===pages;$('export-shortlist').disabled=!counts.fit;$('make-prompt').disabled=!counts.investigate;}
['status-filter','result-search'].forEach(id=>$(id).addEventListener(id==='status-filter'?'change':'input',()=>{page=1;render();}));$('prev-page').addEventListener('click',()=>{page--;render();});$('next-page').addEventListener('click',()=>{page++;render();});
function download(content,name,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export-all').addEventListener('click',()=>download(core.toCsv(results),'network-all-decisions.csv','text/csv;charset=utf-8'));$('export-shortlist').addEventListener('click',()=>download(core.toCsv(results.filter(row=>row.status==='fit'&&!row.locked)),'network-possible-fits.csv','text/csv;charset=utf-8'));
function openReview(id){const row=results.find(row=>row.id===id);if(!row)return;reviewId=id;$('review-title').textContent=row.name||'Unnamed connection';$('review-subtitle').textContent=[row.title,row.company].filter(Boolean).join(' · ')||'No role or company supplied';const detail=$('review-detail');detail.replaceChildren(element('span',labels[row.status],'badge '+row.status),element('p',row.reason));function block(title,items){if(!items.length)return;detail.append(element('h3',title));const ul=element('ul');items.forEach(item=>ul.append(element('li',item)));detail.append(ul);}block('Evidence supplied',row.evidence);block('Still to check',row.unknowns);detail.append(element('h3','Source record'),element('p','Data row '+row.sourceRow));if(row.url)detail.append(element('p',row.url));Object.entries(row.raw).forEach(([key,value])=>{if(value)detail.append(element('p',key+': '+value));});if(row.originalStatus)block('Original decision',[labels[row.originalStatus]+': '+row.originalReason]);if(row.reviewHistory&&row.reviewHistory.length)block('Your review history',row.reviewHistory.map((entry,index)=>'Review '+(index+1)+' · '+labels[entry.status]+' · '+entry.note+' · '+entry.reviewedAt));$('review-edit').hidden=row.locked||row.status==='invalid';$('review-decision').value=['fit','investigate','pass'].includes(row.status)?row.status:'investigate';$('review-note').value=row.reviewNote||'';$('review-status').textContent=row.locked?'This row is locked to preserve do-not-contact or duplicate handling. Update the source CSV if its facts need correction.':row.status==='invalid'?'Correct the source record and run the finder again before reviewing this row.':'';$('review-dialog').showModal();}
$('close-review').addEventListener('click',()=>$('review-dialog').close());$('review-dialog').addEventListener('click',event=>{if(event.target===$('review-dialog')){const rect=event.target.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)event.target.close();}});
$('review-form').addEventListener('submit',event=>{event.preventDefault();const row=results.find(row=>row.id===reviewId);if(!row||row.locked||row.status==='invalid')return;const note=$('review-note').value.trim();if(!note){$('review-status').textContent='Add what you verified before saving your decision.';return;}if(!row.originalStatus){row.originalStatus=row.status;row.originalReason=row.reason;}const nextStatus=$('review-decision').value;row.reviewHistory=row.reviewHistory||[];row.reviewHistory.push({status:nextStatus,note,previousStatus:row.status,previousReason:row.reason,reviewedAt:new Date().toISOString()});row.status=nextStatus;row.reason='Reviewed by you: '+note;row.reviewNote=note;row.priority=row.status==='fit'?(row.engaged===true?3:2):row.status==='investigate'?(row.engaged===true?2:1):null;$('prompt-result').hidden=true;render();$('review-dialog').close();});
$('make-prompt').addEventListener('click',()=>{const candidates=results.filter(row=>row.status==='investigate'&&!row.locked);if(!candidates.length)return;$('prompt-output').value=core.buildReviewPrompt(candidates,activeRules);$('prompt-result').hidden=false;$('prompt-status').textContent=candidates.length+' records included. Add verified source material when you use the prompt.';});$('copy-prompt').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('prompt-output').value);$('prompt-status').textContent='Prompt copied.';}catch(_){$('prompt-output').select();$('prompt-status').textContent='Select and copy the prompt from the field above.';}});$('save-prompt').addEventListener('click',()=>download($('prompt-output').value,'network-buyer-review-prompt.md'));
(data.files||[]).forEach(file=>{const a=element('a',file.path.replace(/^kit\//,''));a.href=file.path;a.download=file.path.split('/').pop();$('file-links').append(a);});
})();
